container:
  image: ubuntu:bionic

task:
  matrix:
    - name: Build on Ubuntu (lz4)
      install_dependencies_script:
        - apt-get update
        - apt-get install -y libonig-dev libpcre3-dev zlib1g-dev libssl-dev libevent-dev gcc make automake bison flex
      script: ./build-test.sh
      container:
        matrix:
          - image: ubuntu:20.04
    - name: Build on Ubuntu (without lz4)
      install_dependencies_script:
        - apt-get update
        - apt-get install -y libonig-dev libpcre3-dev zlib1g-dev libssl-dev libevent-dev gcc make automake bison flex
      script: ./build-test.sh
      container:
        matrix:
          - image: ubuntu:16.04
          - image: ubuntu:18.04
    - name: Build on CentOS (without lz4)
      install_dependencies_script:
        - yum install -y epel-release
        - yum install -y gcc make automake bison flex libtool oniguruma-devel zlib-devel openssl-devel libevent-devel
      script: ./build-test.sh
      container:
        matrix:
          - image: centos:7
#    - name: Build on FreeBSD (lz4)
#      install_dependencies_script:
#        - pkg install -y bash oniguruma pcre libevent gmake automake bison flex
#      script: ./build-test.sh
#      freebsd_instance:
#        matrix:
#          - image: freebsd-12-1-release-amd64
#          - image: freebsd-11-4-release-amd64
    - name: Build on MacOS (lz4)
      install_dependencies_script:
        # oniguruma is useless since onigposix.h isn't shipped
        - brew install lz4 pcre pcre2 libressl libevent
      script: ./build-test.sh
      osx_instance:
        matrix:
          - image: big-sur-base
          - image: catalina-base
